// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yccumznftptilrvdodek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljY3Vtem5mdHB0aWxydmRvZGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxOTUzMDQsImV4cCI6MjA4NDc3MTMwNH0.92nno8ERz45uKQJuvN_0Tw3i517GqMjIQh_hETk8vJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});